### ISSUE TITLE
Get "Infinite" view when Screensharing

### ISSUE THREAD

**Issue by rainoz** [ForstaLabs/relay-web-app#212]
When you turn on Screensharing, if you share the screen that has the Video Conferencing on, you get an infinite screen.  One approach is to NOT show the Shared Screen on the person who is sharing the screen.  For example, Zoom puts a green box around what is being shared to highlight what is being shared.

Attached is what happens with ours, and then how Zoom handles it.

![infinite screen when screen sharing](https://user-images.githubusercontent.com/29361211/42478395-c2378af4-8391-11e8-9119-10a583767d54.jpeg)

<img width="1280" alt="zoom us screenshare" src="https://user-images.githubusercontent.com/29361211/42478309-7e2b6812-8391-11e8-932e-42d1133e7c9e.png">

**Comment by rainoz** [comment]
Zoom is bottom screen (with green rectangle), ours is the infinite.

We need a way to NOT get the inifinite screen when I press screen share.
Many people only have one monitor, and best I can tell if you have one
monitor on ours you will get the infinite screen.

**Comment by rainoz** [comment]
Zoom does give same choices we do (for most part), and based on that they put the green rectangle around it (could be a browser tab or other app)

**Comment by mayfield** [comment]
I'm still missing something here.  In the first attachment I see your desktop running some applications and it has a green halo around it but no call-list to speak of.  It's in our call-list that you see your own video feed/screenshare but I don't see the corresponding user interface for this in your first set of attachments.  

In the last attachment, I see 2 video camera feeds, so I must assume you're talking with one other person and one of those cameras is your own?  If so, where is the corresponding view for this when you are screensharing?  Perhaps that's what you were alluding to in your last comments, but I'm not clear on it.

Ultimately I wonder if this is an apples and oranges thing.  In a normal video call (non webinar) it's par to see your own screenshare in the context of your call list, and yes, it will have video feedback because of the nature of reality.   All the video chats I'm used to using have the same behavior, e.g google hangouts.

I'm also inclined to leave this as-is because it does have some benefits.  Namely screen sharing is not just/only your entire screen.  If you have multiple monitors it could be a single screen, but which one? Or is it both?  It could be one application, it can even be a specific Tab of a browser that's literally not even in view on your current desktop.  This preview gives the user the ability to see and validate the exact contents they are broadcasting.  Without it, they would not be able to validate the veracity of their outgoing video stream and may inadvertently broadcast themselves "without pants."

**Comment by rainoz** [comment]
Hi Justin,
Re: the two video feeds:  That is in "Screensharing" mode.  Just like ours, you select the screen you want to share. Zoom puts the faces of all people on the call with video on like you see Sawyer's and my videos.  That box with the faces can be moved around or minimized if desired.

With multiple screens, I can have those faces, or list of users on the second screen that I am not sharing.  
I've attached two new screenshot (when I was using single computer screen)
-First is other person sharing with me.
-Second is me sharing with that person
In both cases the faces are there but there's still a good view of the screen (and I can minimize that if wanted).

Let's look at Zoom some time when we are both here and we can brainstorm

<img width="1280" alt="screen shot 2018-10-01 at 3 19 16 pm" src="https://user-images.githubusercontent.com/29361211/46317749-4c8c6800-c591-11e8-9694-247ada1d908f.png">
<img width="1280" alt="screen shot 2018-10-01 at 3 13 07 pm" src="https://user-images.githubusercontent.com/29361211/46317761-57df9380-c591-11e8-954f-fb8a0f9433d9.png">

**Comment by mayfield** [comment]
I'll have to use zoom myself to understand this.  I suspect zoom only supports sharing your entire screen and so they just forgo any sort of preview.  We support more options than that and a preview is important.
