### ISSUE TITLE
Screen Share needs to be persistent for all people in a conversation

### ISSUE THREAD

**Issue by rainoz** [ForstaLabs/relay-web-app#214]
When somebody has shared their screen with the people in the conversation, there needs to be a way (or maybe the default behavior) is that at that point the shared screen is what everybody sees, and it doesn't change any more with voices of the different participants.

Only one person on a call should be able to share their screen.  As a first step, others can't share their screen until the person sharing quits sharing.  In the future, potentially the meeting host (the 'initiator') might be able to control who the screen sharer is.

**Comment by mayfield** [comment]
I'm compelled to push back on this in the context of our current `calling` feature due to the side effects it would incur to non webinar use cases (E.g. A forum/debate style of communications vs single-speaker broadcasting).  I believe we discussed at one point that a variant of `calling` could be implemented in the style of an `announcement` thread-type.  This would essentially be built out as a different type of communication altogether, albeit still using WebRTC and camera/microphone, but with a different UX and protocol guidelines.  E.g. The initiator would be bestowed with special powers, etc, etc.

I propose we discuss having two WebRTC based features to handle forum style calling and webinar style broadcasts.

**Comment by rainoz** [comment]
I like your approach of a separate types of video sessions.  Let's grab you, Zach and I and discuss.  Thanks!
RZ

**Comment by mayfield** [comment]
Replacing with #274
