### ISSUE TITLE
Voice/Video: Look for ways to reduce bandwidth and CPU use

### ISSUE THREAD

**Issue by rainoz** [ForstaLabs/relay-web-app#219]
Our default operating mode should be to start a video or audio conversation  in settings where there is limited bandwidth use.  I am using a new MacBook pro and my machine heats up and acts slow when I use video chat.  This will be important for mobile devices as well.

Ideas (some repeated elsewhere):
- Let user choose video or audio when setting up call
- Default for more than 2 people is audio
- Allow mute of incoming video

**Comment by mayfield** [comment]
Just a NOTE about WebRTC parameterization:

We have to be very careful about overprescribing defaults for WebRTC.  Essentially in its unmodified form it attempts to auto-scale and self select the best codecs for any two peers.  That's the meat and potatoes of WebRTC.  By imposing different defaults we effectively disable the autoscaling and best-codec selection algos used by WebRTC impl (eg. the browser in this case).   So I could possibly impose constraints that would yield better cooling properties for your specific test case, but be aware that it will likely cause side effects for other configurations that are more difficult to anticipate.

Regarding mobile devices, they ironically probably have less issues than your laptop because of the aforementioned behavior.  E.g. My mobile chrome device won't use VP8 because it would make the phone catch fire and will instead use H264 which is HW accelerated on basically every phone CPU these days.  So it's entirely possible that you laptop with limited cooling (apple) is a worst case scenario when testing on a local network.

**Comment by mayfield** [comment]
Most of bullets are implemented now (not the 2 person audio limit though).  And the settings page has options to reduce video resolution and framerate which should help for limited platforms too.
