### ISSUE TITLE
Sync on new Device can take a LONG time

### ISSUE THREAD

**Issue by rainoz** [ForstaLabs/relay-web-app#239]
I've had the experience several times when I open a browser on my computer at home (where I may not have used Forsta for some time), that it begins to sync, and it can take a long time (can be over an hour) before I can use the app.

Should be some way to do most recent messages quickly, and the rest asynchronously.  This may be less of an issue once we use a Vault as a sync option

**Comment by mayfield** [comment]
Syncing a new device or an existing one?  The subject line indicates new, but your desc indicates existing device.  There are different techniques for both.  Sadly both are also highly optimized already.  An hour for syncing does seem terrible and I've never experienced anything even remotely close to that with my account which has over 10k messages in it.  So perhaps there is more to this than a normal catching up or sync issue.

**Comment by rainoz** [comment]
Likely existing.  I may have logged in and out of the account, but not used
the device recently.  Suggestions on how to help you debug?

**Comment by mayfield** [comment]
Okay, so it's not a content sync issue.  The device is just processing the incoming queue of messages from signal server.  This has to run from oldest to newest because of signal ratcheting.  It also has to fully process each message one at a time.  So yeah, it can be tediously slow.  I've already spent a lot of time optimizing this path beyond the work done by Signal devs and they have people complaining about the same thing. 

I hate to be the guy that just marks this as wontfix and closes it, but there isn't much more I can do.   If there is a solution it's probably some very creative new approach to the whole thing that I'm not able to think of presently and would most likely be a monumental undertaking.

**Comment by mayfield** [comment]
See: https://github.com/signalapp/Signal-Desktop/issues/1442
